"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Company={id:string;name:string};
type Location={id:string;name:string;code:string};
type Brand={id:string;name:string;location_id:string};
type Integration={id?:string;platform:"zomato"|"swiggy";location_id:string;brand_id:string;merchant_id:string;outlet_id:string;external_store_name:string;integration_mode:string;status:string;auto_accept_orders:boolean;auto_print_kot:boolean;sync_menu:boolean;sync_inventory:boolean;sync_payouts:boolean;last_order_sync_at?:string|null;last_error?:string|null};

function cfg(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)throw new Error("Supabase environment variables are missing.");return{url,key}}
function h(key:string,prefer?:string){return{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(prefer?{Prefer:prefer}:{})}}
const blank=(platform:"zomato"|"swiggy",location_id="",brand_id=""):Integration=>({platform,location_id,brand_id,merchant_id:"",outlet_id:"",external_store_name:"",integration_mode:"partner_api",status:"not_connected",auto_accept_orders:false,auto_print_kot:false,sync_menu:true,sync_inventory:true,sync_payouts:true});

export default function MarketplaceIntegrationsPage(){
 const[company,setCompany]=useState<Company|null>(null);const[locations,setLocations]=useState<Location[]>([]);const[brands,setBrands]=useState<Brand[]>([]);const[integrations,setIntegrations]=useState<Integration[]>([]);const[form,setForm]=useState<Integration>(blank("zomato"));const[saving,setSaving]=useState(false);const[msg,setMsg]=useState("");const[err,setErr]=useState("");
 useEffect(()=>{void load()},[]);
 async function load(){try{const{url,key}=cfg();const cr=await fetch(`${url}/rest/v1/companies?select=id,name&order=created_at.asc&limit=1`,{headers:h(key),cache:"no-store"});if(!cr.ok)throw new Error(await cr.text());const cs=await cr.json() as Company[];if(!cs[0])throw new Error("Create company first.");setCompany(cs[0]);const[lr,br,ir]=await Promise.all([fetch(`${url}/rest/v1/locations?company_id=eq.${cs[0].id}&is_active=eq.true&select=id,name,code&order=name.asc`,{headers:h(key),cache:"no-store"}),fetch(`${url}/rest/v1/brands?company_id=eq.${cs[0].id}&is_active=eq.true&select=id,name,location_id&order=name.asc`,{headers:h(key),cache:"no-store"}),fetch(`${url}/rest/v1/marketplace_integrations?company_id=eq.${cs[0].id}&select=*&order=platform.asc`,{headers:h(key),cache:"no-store"})]);if(!lr.ok||!br.ok||!ir.ok)throw new Error("Unable to load integration setup.");const ls=await lr.json() as Location[];setLocations(ls);setBrands(await br.json());setIntegrations(await ir.json());setForm(blank("zomato",ls[0]?.id||"",""))}catch(e){setErr(e instanceof Error?e.message:"Unable to load integrations.")}}
 const visibleBrands=useMemo(()=>brands.filter(b=>b.location_id===form.location_id),[brands,form.location_id]);
 function edit(i:Integration){setForm({...i});setMsg("");setErr("")}
 async function save(){if(!company||!form.location_id||!form.brand_id)return setErr("Select location and brand.");setSaving(true);setErr("");setMsg("");try{const{url,key}=cfg();const payload={company_id:company.id,...form,updated_at:new Date().toISOString()};const r=await fetch(`${url}/rest/v1/marketplace_integrations?on_conflict=platform,location_id,brand_id`,{method:"POST",headers:h(key,"resolution=merge-duplicates,return=representation"),body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text());const saved=(await r.json() as Integration[])[0];setIntegrations(c=>[...c.filter(x=>!(x.platform===saved.platform&&x.location_id===saved.location_id&&x.brand_id===saved.brand_id)),saved]);setForm(blank(form.platform,form.location_id,""));setMsg("Integration settings saved. Platform API credentials still need partner approval before live orders can sync.")}catch(e){setErr(e instanceof Error?e.message:"Unable to save integration.")}finally{setSaving(false)}}
 const connected=integrations.filter(i=>i.status==="connected").length;
 return <main className="min-h-screen bg-slate-100 p-5 text-slate-950 md:p-8"><div className="mx-auto max-w-7xl space-y-6"><header className="rounded-3xl bg-slate-950 p-7 text-white"><p className="text-sm font-black uppercase tracking-[.18em] text-emerald-400">Marketplace Control</p><h1 className="mt-2 text-3xl font-black">Zomato & Swiggy Integration Center</h1><p className="mt-3 max-w-3xl text-sm text-slate-300">Map every platform outlet to the correct physical location and brand, then control order, menu, inventory, payout and KOT automation.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/" className="rounded-xl bg-white px-4 py-3 text-sm font-black text-slate-950">Main Dashboard</Link><Link href="/orders" className="rounded-xl border border-white/20 px-4 py-3 text-sm font-black">Unified Orders</Link><Link href="/reports/daily" className="rounded-xl border border-white/20 px-4 py-3 text-sm font-black">Daily Reports</Link></div></header>
 <section className="grid gap-4 md:grid-cols-3"><Card t="Configured outlets" v={String(integrations.length)}/><Card t="Connected" v={String(connected)}/><Card t="Pending / Offline" v={String(integrations.length-connected)} danger={integrations.length>connected}/></section>
 <section className="grid gap-6 xl:grid-cols-[420px_1fr]"><div className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Add or update outlet</h2><div className="mt-5 grid gap-3"><select value={form.platform} onChange={e=>setForm(blank(e.target.value as "zomato"|"swiggy",form.location_id,form.brand_id))} className="h-12 rounded-xl border px-4"><option value="zomato">Zomato</option><option value="swiggy">Swiggy</option></select><select value={form.location_id} onChange={e=>setForm({...form,location_id:e.target.value,brand_id:""})} className="h-12 rounded-xl border px-4"><option value="">Select location</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name} ({l.code})</option>)}</select><select value={form.brand_id} onChange={e=>setForm({...form,brand_id:e.target.value})} className="h-12 rounded-xl border px-4"><option value="">Select brand</option>{visibleBrands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><input value={form.external_store_name} onChange={e=>setForm({...form,external_store_name:e.target.value})} placeholder="Platform store name" className="h-12 rounded-xl border px-4"/><input value={form.merchant_id} onChange={e=>setForm({...form,merchant_id:e.target.value})} placeholder="Merchant ID" className="h-12 rounded-xl border px-4"/><input value={form.outlet_id} onChange={e=>setForm({...form,outlet_id:e.target.value})} placeholder="Outlet / Restaurant ID" className="h-12 rounded-xl border px-4"/><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="h-12 rounded-xl border px-4"><option value="not_connected">Not connected</option><option value="pending">Pending approval</option><option value="connected">Connected</option><option value="paused">Paused</option><option value="error">Error</option></select>{[["auto_accept_orders","Auto accept orders"],["auto_print_kot","Auto print KOT"],["sync_menu","Sync menu"],["sync_inventory","Sync stock availability"],["sync_payouts","Sync payouts"]].map(([k,l])=><label key={k} className="flex items-center gap-3 rounded-xl border p-3"><input type="checkbox" checked={Boolean(form[k as keyof Integration])} onChange={e=>setForm({...form,[k]:e.target.checked})}/><span className="font-bold">{l}</span></label>)}<button onClick={()=>void save()} disabled={saving} className="h-12 rounded-xl bg-slate-950 font-black text-white disabled:opacity-50">{saving?"Saving...":"Save integration"}</button></div>{msg?<p className="mt-4 rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{msg}</p>:null}{err?<p className="mt-4 rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{err}</p>:null}</div>
 <div className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Platform outlets</h2><div className="mt-5 space-y-3">{integrations.map((i,idx)=>{const l=locations.find(x=>x.id===i.location_id);const b=brands.find(x=>x.id===i.brand_id);return <button key={`${i.platform}-${i.location_id}-${i.brand_id}-${idx}`} onClick={()=>edit(i)} className="flex w-full flex-col gap-3 rounded-2xl border p-5 text-left md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-black ${i.platform==="zomato"?"bg-red-50 text-red-700":"bg-orange-50 text-orange-700"}`}>{i.platform.toUpperCase()}</span><span className={`rounded-full px-3 py-1 text-xs font-black ${i.status==="connected"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{i.status.replaceAll("_"," ")}</span></div><p className="mt-2 font-black">{b?.name||"Unknown brand"} · {l?.name||"Unknown location"}</p><p className="mt-1 text-sm text-slate-500">{i.external_store_name||"Store name not added"} · Outlet ID {i.outlet_id||"pending"}</p></div><div className="text-sm text-slate-500"><p>Auto accept: <b>{i.auto_accept_orders?"On":"Off"}</b></p><p>Auto KOT: <b>{i.auto_print_kot?"On":"Off"}</b></p></div></button>})}{!integrations.length?<p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">No Zomato or Swiggy outlet has been configured yet.</p>:null}</div></div></section>
 <section className="rounded-3xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900"><b>Live connection requirement:</b> Zomato and Swiggy do not provide open public merchant APIs for direct self-service connection. Live order acceptance, menu publishing and payout sync require approved partner credentials, an aggregator connection, or official webhook/API access. This screen prepares the mapping and controls without storing secret API tokens in the browser.</section></div></main>}
function Card({t,v,danger=false}:{t:string;v:string;danger?:boolean}){return <div className={`rounded-2xl p-5 shadow-sm ${danger?"bg-amber-50":"bg-white"}`}><p className="text-sm font-bold text-slate-500">{t}</p><p className="mt-2 text-3xl font-black">{v}</p></div>}
