"use client";

import { ChangeEvent, useEffect, useMemo, useState } from "react";
import * as XLSX from "xlsx";

type Company={id:string;name:string};
type Location={id:string;name:string;code:string};
type Brand={id:string;name:string;location_id:string};
type Target={locationId:string;brandId:string};
type MenuRow={name:string;onlineName:string;description:string;sku:string;category:string;price:number;itemType:"veg"|"non_veg"|"egg";packing:number;addonGroups:string[];error?:string};
type AddonRow={groupName:string;groupCode:string;minSelect:number;maxSelect:number;required:boolean;name:string;sku:string;price:number;taxRate:number;itemType:string;active:boolean;error?:string};

const txt=(v:unknown)=>String(v??"").trim();
const num=(v:unknown,f=0)=>{const n=Number(v);return Number.isFinite(n)?n:f};
const yes=(v:unknown,d=true)=>{const s=txt(v).toLowerCase();return s?['yes','y','true','1','active'].includes(s):d};
const kind=(v:unknown):"veg"|"non_veg"|"egg"=>{const s=txt(v).toLowerCase();return s.includes('non')?'non_veg':s==='egg'?'egg':'veg'};
function cfg(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)throw new Error('Supabase environment variables are missing.');return{url,key}}
function h(key:string,prefer?:string){return{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(prefer?{Prefer:prefer}:{})}}

export default function PetpoojaImportPage(){
 const[company,setCompany]=useState<Company|null>(null);const[locations,setLocations]=useState<Location[]>([]);const[brands,setBrands]=useState<Brand[]>([]);const[targets,setTargets]=useState<Target[]>([]);
 const[menuRows,setMenuRows]=useState<MenuRow[]>([]);const[addonRows,setAddonRows]=useState<AddonRow[]>([]);const[menuFile,setMenuFile]=useState('');const[addonFile,setAddonFile]=useState('');const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[err,setErr]=useState('');
 useEffect(()=>{void load()},[]);
 async function load(){try{const{url,key}=cfg();const cr=await fetch(`${url}/rest/v1/companies?select=id,name&order=created_at.asc&limit=1`,{headers:h(key)});const cs=await cr.json() as Company[];if(!cs[0])throw new Error('Create company first.');setCompany(cs[0]);const[lr,br]=await Promise.all([fetch(`${url}/rest/v1/locations?company_id=eq.${cs[0].id}&select=id,name,code&is_active=eq.true&order=name.asc`,{headers:h(key)}),fetch(`${url}/rest/v1/brands?company_id=eq.${cs[0].id}&select=id,name,location_id&is_active=eq.true&order=name.asc`,{headers:h(key)})]);setLocations(await lr.json());setBrands(await br.json())}catch(e){setErr(e instanceof Error?e.message:'Unable to load setup.')}}
 function toggle(l:string,b:string){setTargets(c=>c.some(x=>x.locationId===l&&x.brandId===b)?c.filter(x=>!(x.locationId===l&&x.brandId===b)):[...c,{locationId:l,brandId:b}])}
 async function rows(file:File){const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});let ws=wb.Sheets[wb.SheetNames[0]];let data=XLSX.utils.sheet_to_json<Record<string,unknown>>(ws,{defval:''});if(!data.length||Object.keys(data[0]).length<3){const raw=XLSX.utils.sheet_to_json<unknown[]>(ws,{header:1,defval:''});const headerIndex=raw.findIndex(r=>Array.isArray(r)&&r.some(x=>txt(x)==='Addon_Group_Name'));if(headerIndex>=0){ws=XLSX.utils.aoa_to_sheet(raw.slice(headerIndex));data=XLSX.utils.sheet_to_json<Record<string,unknown>>(ws,{defval:''});}}return data}
 async function readMenu(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setMenuFile(f.name);setErr('');try{const data=await rows(f);const parsed=data.map(r=>{const name=txt(r.Online_Name)||txt(r.Name);const sku=(txt(r.Short_Code)||txt(r.Short_Code_2)||txt(r.Sap_Code)||name).toUpperCase();const price=num(r.Price,-1);const groups=txt(r.Addon_Group_Name).split(/[|,;]/).map(x=>x.trim()).filter(Boolean);const p:string[]=[];if(!name)p.push('Name missing');if(!sku)p.push('SKU missing');if(price<0)p.push('Price invalid');return{name,onlineName:txt(r.Online_Name),description:txt(r.Description),sku,category:txt(r.Category)||txt(r.Parent_Category),price,itemType:kind(r.Attributes),packing:Math.max(0,num(r.Packing_Charges)),addonGroups:groups,error:p.join(', ')||undefined}});setMenuRows(parsed)}catch(e){setErr(e instanceof Error?e.message:'Unable to read menu file.')}}
 async function readAddons(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setAddonFile(f.name);setErr('');try{const data=await rows(f);const parsed=data.map((r,i)=>{const groupName=txt(r.Addon_Group_Name);const name=txt(r.Addon_Item_Name);const code=(txt(r.Addon_Group_Id)||groupName||`GROUP-${i+1}`).toUpperCase().replace(/[^A-Z0-9]+/g,'-');const sku=(txt(r.Sapcode)||`${code}-${name}`).toUpperCase().replace(/[^A-Z0-9]+/g,'-');const price=num(r.Addon_Item_Price,-1);const p:string[]=[];if(!groupName)p.push('Group missing');if(!name)p.push('Addon missing');if(price<0)p.push('Price invalid');return{groupName,groupCode:code,minSelect:Math.max(0,num(r.Addon_Min)),maxSelect:Math.max(1,num(r.Addon_Max,1)),required:num(r.Addon_Min)>0,name,sku,price,taxRate:5,itemType:txt(r.Attribute),active:yes(r.Addon_item_status),error:p.join(', ')||undefined}});setAddonRows(parsed)}catch(e){setErr(e instanceof Error?e.message:'Unable to read addon file.')}}
 async function importAll(){if(!company||!targets.length)return setErr('Select at least one location and brand.');const vm=menuRows.filter(x=>!x.error),va=addonRows.filter(x=>!x.error);if(!vm.length&&!va.length)return setErr('Upload valid menu or addon file.');setBusy(true);setErr('');setMsg('');try{const{url,key}=cfg();for(const t of targets){if(vm.length){const p=vm.map(x=>({company_id:company.id,location_id:t.locationId,brand_id:t.brandId,name:x.name,sku:x.sku,description:x.description||null,item_type:x.itemType,base_price:x.price,packaging_charge:x.packing,tax_rate:5,is_active:true,available_on_pos:true,available_on_zomato:true,available_on_swiggy:true,updated_at:new Date().toISOString()}));const r=await fetch(`${url}/rest/v1/menu_items?on_conflict=brand_id,sku`,{method:'POST',headers:h(key,'resolution=merge-duplicates,return=minimal'),body:JSON.stringify(p)});if(!r.ok)throw new Error(await r.text())}
 if(va.length){const groups=[...new Map(va.map(x=>[x.groupCode,x])).values()];const gp=groups.map(x=>({company_id:company.id,location_id:t.locationId,brand_id:t.brandId,name:x.groupName,code:x.groupCode,min_select:x.minSelect,max_select:x.maxSelect,is_required:x.required,is_active:true,updated_at:new Date().toISOString()}));let r=await fetch(`${url}/rest/v1/addon_groups?on_conflict=brand_id,code`,{method:'POST',headers:h(key,'resolution=merge-duplicates,return=representation'),body:JSON.stringify(gp)});if(!r.ok)throw new Error(await r.text());const gm=new Map(((await r.json()) as {id:string;code:string}[]).map(x=>[x.code,x.id]));const ap=va.map(x=>({company_id:company.id,location_id:t.locationId,brand_id:t.brandId,addon_group_id:gm.get(x.groupCode),name:x.name,sku:x.sku,price:x.price,tax_rate:x.taxRate,is_active:x.active,updated_at:new Date().toISOString()}));r=await fetch(`${url}/rest/v1/addon_items?on_conflict=brand_id,sku`,{method:'POST',headers:h(key,'resolution=merge-duplicates,return=minimal'),body:JSON.stringify(ap)});if(!r.ok)throw new Error(await r.text());
 const mr=await fetch(`${url}/rest/v1/menu_items?brand_id=eq.${t.brandId}&select=id,sku`,{headers:h(key)});const mm=new Map(((await mr.json()) as {id:string;sku:string}[]).map(x=>[x.sku,x.id]));const links:any[]=[];for(const m of vm){for(const gname of m.addonGroups){const g=groups.find(x=>x.groupName.toLowerCase()===gname.toLowerCase());const menuId=mm.get(m.sku);const groupId=g?gm.get(g.groupCode):undefined;if(menuId&&groupId)links.push({menu_item_id:menuId,addon_group_id:groupId});}}if(links.length){r=await fetch(`${url}/rest/v1/menu_item_addon_groups?on_conflict=menu_item_id,addon_group_id`,{method:'POST',headers:h(key,'resolution=ignore-duplicates,return=minimal'),body:JSON.stringify(links)});if(!r.ok)throw new Error(await r.text())}}
 }setMsg(`Updated ${targets.length} target(s): ${vm.length} menu items and ${va.length} addons.`)}catch(e){setErr(e instanceof Error?e.message:'Import failed.')}finally{setBusy(false)}}
 const grouped=useMemo(()=>{const m=new Map<string,AddonRow[]>();addonRows.forEach(a=>m.set(a.groupName,[...(m.get(a.groupName)||[]),a]));return m},[addonRows]);
 return <main className="min-h-screen bg-slate-100 p-5 text-slate-950 md:p-8"><div className="mx-auto max-w-7xl space-y-6"><header className="rounded-3xl bg-slate-950 p-7 text-white"><p className="text-sm font-black uppercase tracking-[.18em] text-emerald-400">Petpooja CSV Import</p><h1 className="mt-2 text-3xl font-black">Upload menu and addon files in your existing format</h1></header>
 <section className="rounded-3xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-black">1. Select locations and brands</h2><div className="flex gap-2"><button onClick={()=>setTargets(brands.map(b=>({locationId:b.location_id,brandId:b.id})))} className="rounded-xl border px-4 py-2 font-bold">Select all</button><button onClick={()=>setTargets([])} className="rounded-xl border px-4 py-2 font-bold">Clear</button></div></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{locations.map(l=><article key={l.id} className="rounded-2xl border p-5"><p className="text-xs font-black text-emerald-600">{l.code}</p><h3 className="text-lg font-black">{l.name}</h3><div className="mt-3 space-y-2">{brands.filter(b=>b.location_id===l.id).map(b=>{const c=targets.some(x=>x.locationId===l.id&&x.brandId===b.id);return <label key={b.id} className={`flex gap-3 rounded-xl border p-3 ${c?'border-emerald-500 bg-emerald-50':''}`}><input type="checkbox" checked={c} onChange={()=>toggle(l.id,b.id)}/><span className="font-bold">{b.name}</span></label>})}</div></article>)}</div></section>
 <section className="grid gap-5 md:grid-cols-2"><label className="rounded-3xl border-2 border-dashed bg-white p-8 text-center"><b>2A. Upload Petpooja Menu CSV</b><p className="mt-2 text-emerald-700">{menuFile||'Choose file'}</p><input type="file" accept=".csv,.xlsx,.xls" onChange={readMenu} className="mt-4"/></label><label className="rounded-3xl border-2 border-dashed bg-white p-8 text-center"><b>2B. Upload Petpooja Addon CSV</b><p className="mt-2 text-emerald-700">{addonFile||'Choose file'}</p><input type="file" accept=".csv,.xlsx,.xls" onChange={readAddons} className="mt-4"/></label></section>
 {(menuRows.length||addonRows.length)?<section className="rounded-3xl bg-white p-6"><h2 className="text-xl font-black">3. Integrated preview</h2><p className="mt-2 text-sm text-slate-500">{menuRows.length} menu items · {addonRows.length} addon rows · {grouped.size} addon groups</p><div className="mt-4 max-h-96 overflow-auto rounded-xl border"><table className="w-full text-sm"><thead className="sticky top-0 bg-slate-100"><tr><th className="p-3 text-left">Menu item</th><th className="p-3 text-left">SKU</th><th className="p-3 text-left">Price</th><th className="p-3 text-left">Addon groups</th></tr></thead><tbody>{menuRows.map((m,i)=><tr key={i} className="border-t"><td className="p-3 font-bold">{m.name}</td><td className="p-3">{m.sku}</td><td className="p-3">₹{m.price}</td><td className="p-3">{m.addonGroups.join(', ')||'Not linked in menu file'}</td></tr>)}</tbody></table></div><button onClick={importAll} disabled={busy||!targets.length} className="mt-5 h-12 w-full rounded-xl bg-slate-950 font-black text-white disabled:opacity-50">{busy?'Updating...':'Update selected locations / brands'}</button></section>:null}
 {msg&&<p className="rounded-xl bg-emerald-50 p-4 font-bold text-emerald-700">{msg}</p>}{err&&<p className="rounded-xl bg-red-50 p-4 font-bold text-red-700">{err}</p>}</div></main>
}
